config/routes.rb
Clique::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :admins, :except=>[:new, :create, :destroy, :update, :show, :edit]
  mount RailsAdmin::Engine => '/wxztswe1', :as => 'rails_admin'

  root :to => "home#index"

  get '/i/:id'=>"images#show", :as=>:image_slug
  resources :images, :except=>[:create, :new, :destroy, :update] do
    resources :comments, :except=>[:show, :new, :index, :update]
  end

  resources :faqs, :only=>[:index], :as=>:faq
  get '/mobile/user' => "Mobile::User#index", :as=>:mobile_user_show
  get '/mobile/top' => "Mobile::User#top_nspre", :as=>:top_nspre
  get '/verify/email' => "Emails#verify_other", :as=>:verify_other_email

  resource :setting, :only=>[:show,:edit, :update]

  match '/mobile/register' => "api::Mobile#register", :as=>:api_mobile_register
  post '/mobile/image/upload' =>"api::Mobile#image", :as=>:api_mobile_image_upload

  get '/dashboard' => "dashboard#index", :as=>:dashboard

  get '/profile/:id' => "users#profile", :as=>:profile

  get '/noprofile' => "static_pages#no_profile", :as=>:no_profile

  post '/search'=>"search#show", :as=>:search

  post '/images/favorite/:id' => "images#favorited", :as=>:favorite_image
  post '/image/follow/:id' => "images#follow", :as=>:follow_user
  post '/image/unfollow/:id' => "images#unfollow", :as=>:unfollow_user

  get '/about'=>"static_pages#about", :as=>:about

  get '/:slug' => "images#thumb", :as=>:display_thumb
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :image
  belongs_to :user
  acts_as_voteable
  validates_length_of :body, :maximum=>255, :message=>"Comments must be less then 255 characters", :allow_blank => false
  after_save :update_cache

  def avatar_profile_url
    if self.user_id.blank?
      "gravatar.png"
    else
      user = User.find self.user_id

      if user.facebook_id.present?
        "http://graph.facebook.com/#{user.facebook_id}/picture"
      else
        "gravatar.png"
      end
    end
  end

  def update_cache
    Rails.cache.delete("comments_image_#{self.image_id}")
  end
end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :user
  validates_uniqueness_of :email, :scope=>:user_id

  def generate_token
    self.verify_token||= SecureRandom.hex(24)
  end

end

app/models/faq.rb
class Faq < ActiveRecord::Base
  validates_uniqueness_of :name

end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :file, ImagesUploader
  before_save :generate_slugs
  belongs_to :user
  has_many :comments, :dependent => :destroy
  acts_as_taggable
  acts_as_voteable
  after_save :do_after

  def generate_slugs
    #Unqiue Slug
    loop do
      _slug = String.random_alphanumeric(7)
      if Image.find_by_slug(_slug) == nil
        self.slug = _slug
        break
      end
    end if self.slug.blank?

    self.delete_token = String.random_alphanumeric(7) if self.delete_token.blank?
    #self.md5=Digest::MD5.hexdigest( File.read( self.file.current_path ) ) if self.md5.blank?
    #Rails.cache.delete("gallery_images")
    #Rails.cache.delete("comments_image_#{self.id}")
  end

  def do_after
    if self.front_page?
      #send out front page newsletter
      if self.user.setting.newsletter? #send email
        Notifier.delay.front_page(self.id)
      end
    end
  end

end

app/models/news.rb
class News < ActiveRecord::Base
  after_save :do_after


  def do_after
    Rails.cache.delete("news_feed")
  end

end

app/models/setting.rb
class Setting < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :facebook_access_token, :facebook_id, :nickname, :name

  before_save :generate_token
  after_create :post_create
  has_many :images, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  acts_as_voter
  has_karma(:images, :as=>:submitter, :weight=>0.3)
  has_karma(:comments, :as=>:submitter, :weight=>0.3)
  acts_as_follower
  acts_as_followable
  validates_uniqueness_of :nickname
  has_one :setting, :dependent => :destroy
  has_many :emails, :dependent => :destroy

  def avatar_profile_url
    if self.facebook_id.blank?
      "gravatar.png"
    else
      "http://graph.facebook.com/#{self.facebook_id}/picture"
    end
  end

  def has_nickname?
   not self.nickname.blank?
  end

  def generate_token
    self.mobile_token||=SecureRandom.hex(24) #if self.mobile_token.blank?

    loop do
      _slug = String.random_alphanumeric(7)
      if User.find_by_slug(_slug) == nil
        self.slug = _slug
        break
      end
    end if self.slug.blank?

  end

  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token.extra.raw_info
    if user = User.where(:email => data.email).first
      user.facebook_access_token = access_token['credentials']['token']
      if user.full_size_image_slots != 3 or user.email_slots != 6
        user.full_size_image_slots=3
        user.email_slots = 6
        user.save!
      end
      user
    else # Create a user with a stub password.
      pword = Devise.friendly_token[0,8]
      user = User.new(:email => data.email, :password => pword, :facebook_access_token=>access_token['credentials']['token'], :facebook_id => access_token['uid'], :name=>data['name'] )
      user.confirm!
      Notifier.delay.send_password_facebook_login(pword,data.email)
      if user.full_size_image_slots != 3 or user.email_slots != 6
        user.full_size_image_slots=3
        user.email_slots = 6
        user.save!
      end
      user # If account is through facebook I don't want to send out a confirm email thats gay
    end
  end

  def facebook
    @fb_user ||= FbGraph::User.me(current_user.facebook_access_token)
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"]
      end
      user.facebook_access_token = session["devise.facebook_data"]['credentials']['token'] if data = session["devise.facebook_data"] && session["devise.facebook_data"]['credentials']['token']
    end
  end

  private

  def post_create
    # I want to create the user settings
    self.setting = Setting.new
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base

  scope :for_voter, lambda { |*args| where(["voter_id = ? AND voter_type = ?", args.first.id, args.first.class.name]) }
  scope :for_voteable, lambda { |*args| where(["voteable_id = ? AND voteable_type = ?", args.first.id, args.first.class.name]) }
  scope :recent, lambda { |*args| where(["created_at > ?", (args.first || 2.weeks.ago)]) }
  scope :descending, order("created_at DESC")

  belongs_to :voteable, :polymorphic => true
  belongs_to :voter, :polymorphic => true

  attr_accessible :vote, :voter, :voteable


  # Comment out the line below to allow multiple votes per user.
  validates_uniqueness_of :voteable_id, :scope => [:voteable_type, :voter_type, :voter_id]

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/notifier/add_email.html.erb
Hi,
<p>
This email was sent to you from nsprme.com, a photo sharing service. This person with the email address: <%= @user.email %> <%= @user.name || ''  %> would
like to send you an email that contains pictures they take from their mobile phone. If this is ok with you please click
on the link below marked confirm. If you do not want to receive emails from this person then ignore this email. If you
feel this email was sent as SPAM or maliciously please report it by clicking on the link marked REPORT and we will investigate.
</p>
<b>CONFIRM</b>: <%= link_to( "Click here to confirm", verify_other_email_url(:email=>@to_email, :token=>@code) ) %>
<br />
<b>REPORT</b>: Forward this email to <a href="mailto:support@nsprme.com">support@nsprme.com</a>.
<br />
<p>
 You can view the persons profile <%= link_to( "here", profile_url(:id=>@user.slug) ) %>.
 </p>
Thank you,<br />
<a href="http://www.nsprme.com">Nsprme.com</a><br />
<i>"What Inspires You?"</i>

app/views/notifier/add_email.text.erb
Hi,

This email was sent to you from nsprme.com, a photo sharing service. This person with the email address: <%= @user.email %> <%= @user.name || ''  %> would
like to send you an email that contains pictures they take from their mobile phone. If this is ok with you please click
on the link below marked confirm. If you do not want to receive emails from this person then ignore this email. If you
feel this email was sent as SPAM or maliciously please report it by clicking on the link marked REPORT and we will investigate.

CONFIRM: <%= verify_other_email_url(:email=>@to_email, :token=>@code) %>

REPORT: Forward this email to support@nsprme.com

Thank you,
Nsprme.com
"What Inspires You?"

app/views/notifier/comment_added.text.erb
Hi,

Someone saw your photo on nsprme.com and left a comment. Keep submitting your photos and continue to inspire others.

Photo URL: <%= image_slug_url(:id=>@image.slug) %>

Share this photo on your twitter or facebook feed. Go into Nsprme select the photo and click on 'share'.

To discontinue receiving these emails respond to support@nsprme.com or change your settings in setting goto nsprme.com login and uncheck 'Newsletter'. You will not receive anymore emails.

Soon you will be able to access this on your phone. Nsprme is a continued work in progress and we value all your feedback.

Thanks,
Npsrme.com

app/views/notifier/following.text.erb
Hi,

Someone saw your photo on nsprme.com and decided to follow you. Keep submitting your photos and continue to inspire others.

Photo URL: <%= image_slug_url(:id=>@image.slug) %>

Share this photo on your twitter or facebook feed. Go into Nsprme select the photo and click on 'share'.

To discontinue receiving these emails respond to support@nsprme.com or change your settings in setting goto nsprme.com login and uncheck 'Newsletter'. You will not receive anymore emails.

Soon you will be able to access this on your phone. Nsprme is a continued work in progress and we value all your feedback.

Thanks,
Npsrme.com

app/views/notifier/front_page.text.erb
Hi,

Your photo was selected to be on the front page of nsprme.com. Congratulation our photos are hand picked to make sure only the best show up on the front page. Keep submitting your photos and continue to inspire others.

Photo URL: <%= image_slug_url(:id=>@image.slug) %>

Share this photo on your twitter or facebook feed. Go into Nsprme select the photo and click on 'share'.

To discontinue receiving these emails respond to support@nsprme.com or change your settings in setting goto nsprme.com login and uncheck 'Newsletter'. You will not receive anymore emails.

Soon you will be able to access this on your phone. Nsprme is a continued work in progress and we value all your feedback.

Thanks,
Npsrme.com

app/views/notifier/send_inspired.text.erb
Hi,

Someone saw your photo on nsprme.com and found it inspiring. Keep submitting your photos and continue to inspire others.

Photo URL: <%= image_slug_url(:id=>@image.slug) %>

Share this photo on your twitter or facebook feed. Go into Nsprme select the photo and click on 'share'.

To discontinue receiving these emails respond to support@nsprme.com or change your settings in setting goto nsprme.com login and uncheck 'Newsletter'. You will not receive anymore emails.

Soon you will be able to access this on your phone. Nsprme is a continued work in progress and we value all your feedback.

Thanks,
Npsrme.com

app/views/notifier/send_password_facebook_login.text.erb
Hi,

You registered on the website via facebook login. We didn't find a record with you logging in from your
mobile device first. Please keep this password in a secure location. If you decide to download the program
and login from the mobile device you will need this password.

Password: <%= @password %>

Please keep this in a secure location and don't lose it. If you need any help please contact support@nsprme.com.

Sincerely,

nsprme.com

app/views/topbottom/_activity_feed.html.erb
		<div class="one_third last">
		<div class="box widget">
				<h3>Activity Feed</h3>
				<p>Check out the latest happenings</p>
				<p class="small_block">Sam got the layout working</p>
			</div>
		</div>

app/views/topbottom/_archives.html.erb
		<div class="one_third">

		<div class="box_small box widget widget_categories" ><h3 class="widgettitle">Categories</h3>
			<ul>
				<li><a href="index.html">Network News</a></li>
				<li><a href="blog.html">Web Design &amp; Development</a></li>
				<li><a href="single.html">Adobe Creative Suite 4</a></li>
				<li><a href="fullwidth.html">Dreamweaver CS4</a></li>
				<li><a href="page.html">jQuery - Write less do more</a></li>
				<li><a href="fullwidth.html">Mootools - A compact javascript framework</a></li>
			</ul>
		</div>




		<div class="box_small box widget widget_archive" ><h3 class="widgettitle">Archives</h3>
			<ul>
				<li><a title="March 2010" href="archive.html">March 2010</a></li>
				<li><a title="February 2010" href="archive.html">February 2010</a></li>
				<li><a title="January 2010" href="archive.html">January 2010</a></li>
			</ul>
		</div>
		</div>

app/views/topbottom/_footer.html.erb
<div id="footer_bottom" class="wrapper">

	<div class="center">
		<span class="copyright">Copyright &copy; 2012</span>
	<!-- end center -->
	</div>

<!-- end footer -->
</div>

app/views/topbottom/_header.html.erb
<div class="wrapper" id='wrapper_head'>

	<div class="center">

		<div id="head">

			<h1 class="logo"><a href="index.html" class='ie6fix'>CleanCut</a></h1>
			<ul id="nav">
				<li class='current' id='home'><%= link_to("Home", root_url ) %></li>
                <li><a href="http://blog.nsprme.com">Blog</a></li>
				<li><%= link_to( "About", about_url )%></li>
			</ul>


			<div id="headextras" class='rounded'>

               <div id="login">
                 <% if not user_signed_in? %>
                    <%= link_to( "Login", new_user_session_url) %> or <%= link_to("Create Account", new_user_registration_url )%>. Forgot your <%= link_to("password", new_user_confirmation_url )%>?
                 <% else %>
                    Welcome back! Goto <%= link_to("Settings", edit_setting_url) %>. <%= link_to("Logout", destroy_user_session_path, :method=>:delete) %>
                 <% end %>
                     </div>

				<ul class="social_bookmarks">
					<!--<li class='facebook'><a class='ie6fix' href="#">Facebook</a></li>-->
                  <li class='facebook'><%= link_to "Facebook", user_omniauth_authorize_path(:facebook), :class=>"ie6fix" %></li>
					<!--<li class='rss'><a class='ie6fix' href="#">RSS</a></li>-->
					<!--<li class='twitter'><a class='ie6fix' href="#">Twitter</a></li>-->
				</ul><!-- end social_bookmarks-->

			<!-- end headextras: -->
			</div>


		<!--end head-->
		</div>

	<!-- end center-->
	</div>
<!--end wrapper-->
</div>

app/views/topbottom/_news.html.erb
<div class="one_third">

    <div class="box_small box widget community_news"><h3 class="widgettitle">Latest News</h3>
    <div class="entry box_entry">
    <h4><a href="single.html">Nspireme.com launches!</a></h4>

    <a href="single.html"><img title="Hello world!" alt="" src="assets/files/mini_pic2.jpg" class="rounded alignleft"/></a><p>New social picture site opens with limited slots available for early adopters. Sign up today and guarantee your spot.</p>
    </div>
    </div>

</div>