config/routes.rb
Clique::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :admins, :except=>[:new, :create, :destroy, :update, :show, :edit]
  mount RailsAdmin::Engine => '/wxztswe1', :as => 'rails_admin'

  root :to => "home#index"

  get '/i/:id'=>"images#show", :as=>:image_slug
  resources :images, :except=>[:create, :new, :destroy, :update] do
    resources :comments, :except=>[:show, :new, :index, :update]
  end

  resources :faqs, :only=>[:index], :as=>:faq
  get '/mobile/user' => "Mobile::User#index", :as=>:mobile_user_show
  get '/mobile/top' => "Mobile::User#top_nspre", :as=>:top_nspre
  get '/verify/email' => "Emails#verify_other", :as=>:verify_other_email

  resource :setting, :only=>[:show,:edit, :update]

  match '/mobile/register' => "api::Mobile#register", :as=>:api_mobile_register
  post '/mobile/image/upload' =>"api::Mobile#image", :as=>:api_mobile_image_upload

  get '/dashboard' => "dashboard#index", :as=>:dashboard

  get '/profile/:id' => "users#profile", :as=>:profile

  get '/noprofile' => "static_pages#no_profile", :as=>:no_profile

  post '/search'=>"search#show", :as=>:search

  post '/images/favorite/:id' => "images#favorited", :as=>:favorite_image
  post '/image/follow/:id' => "images#follow", :as=>:follow_user
  post '/image/unfollow/:id' => "images#unfollow", :as=>:unfollow_user

  get '/about'=>"static_pages#about", :as=>:about

  get '/:slug' => "images#thumb", :as=>:display_thumb
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @news = News.where(:active=>true).order("created_at DESC")


    @images = Image.where(:front_page=>true).order("created_at DESC").page params[:page]
    @activity = nil #ActivityFeed.get_feed

  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_activity_feed.html.erb
<div class="box">
    <h3>What's happening?</h3>
    <ul>
        <% @activity.each do |feed| %>
            <li><%=feed %></li>
        <% end %>
    </ul>
</div>

app/views/home/_gallery_comment.html.erb
<% unless image.comments.blank? %>
<div style="margin-left: 3px; margin-right: 3px;">
  <ul>
    <% image.comments.sample(3).each do |comment| %>
        <li style="background: transparent;"><%= image_tag(comment.user.avatar_profile_url, :width=>20, :height=>20) %><span style="padding-left: 3px;"><%= truncate( comment.body, :length=>55 ) %></span></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/home/_gallery_entry.html.erb
<div class="gallery_entry <%="last" if [2,5,8].include?(image_counter) %>" style="position: relative;">

    <div class="gallery_inner" style="position: relative;">

        <a class='preloading gallery_image' href="<%=image_slug_url(image.slug) %>">
            <!--<span class="featured_entry"></span>-->
            <%= image_tag( image.file.gallery.url, :class=>"item_small" ) %>
            <%= image_tag( image.file.url, :class=>"item_big no_preload") %>
        </a>
        <span class='comment_link'><%=image.comments.count %></span>
        <div class='comment_link' style="position: absolute; left: 9px; top: 148px; width: 96px; background:  transparent;">
           <%= image.plusminus %>  Nspre'd
        </div>


    </div>

  <h3><%= image.caption.blank? ? nil : image.caption %></h3>
  <%= render "gallery_comment", :image=>image  %>

</div>

app/views/home/_news_item.html.erb
<div class="entry box_entry">
<h4><a href="single.html"><%=news.headline %></a></h4>

<p><%=news.body %></p>
</div>

app/views/home/_search_box.html.erb
<div class="box_small box widget community_news"><h3 class="widgettitle">Search</h3>
<%= form_tag(search_url, :method=>:post) do %>
    <%= text_field_tag :terms, nil, :placeholder=>"Comma separated search terms", :size=>30 %> <br />
    <%= submit_tag "Search" %>
<% end %>
</div>

app/views/home/index.html.erb
<%= render :partial=>"topbottom/header" %>

<div class="wrapper" id='wrapper_main'>

	<div class="center">



		<div id="main">

			<div class="content the_gallery">

				<div class="entry"> <!-- This is the Featured row -->
                    <%= render :partial => "gallery_entry", :collection => @images[0..2], :as=>"image" %>
                </div>

              	<div class="entry"> <!-- This is the Featured row -->
                    <%= render :partial => "gallery_entry", :collection => @images[3..5], :as=>"image" %>
                </div>

              	<div class="entry"> <!-- This is the Featured row -->
                    <%= render :partial => "gallery_entry", :collection => @images[6..8], :as=>"image" %>
                </div>

                <%= paginate @images %>
            </div> <!-- End Content -->


          <div class="sidebar">
            <% #render :partial => "activity_feed" %>
            <%= render :partial => "search_box" %>
          </div> <!-- End Sidebar -->

          <div class="sidebar">
            <div class="box_small box widget community_news">
            <h2>Share</h2>
              <a href="https://twitter.com/themorningdump" class="twitter-follow-button" data-show-count="false">Follow @themorningdump</a>
              <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
                <br />
                <div class="fb-like" data-href="http://www.facebook.com/nsprme" data-send="true" data-layout="button_count" data-width="450" data-show-faces="true"></div>
            </div>
          </div>
          
          <div class="sidebar">
            <div class="box_small box widget community_news">
              <h2>Support</h2>
              For support please email <a href="mailto:support@nsprme.com">support@nsprme.com</a>. I will respond within 24 hours.
            </div>
          </div>

        </div>  <!-- End Main -->
    </div> <!-- End Center -->

    </div> <!-- Main Wrapper -->
<%= render :partial => "topbottom/footer" %>