config/routes.rb
Clique::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :admins, :except=>[:new, :create, :destroy, :update, :show, :edit]
  mount RailsAdmin::Engine => '/wxztswe1', :as => 'rails_admin'

  root :to => "home#index"

  get '/i/:id'=>"images#show", :as=>:image_slug
  resources :images, :except=>[:create, :new, :destroy, :update] do
    resources :comments, :except=>[:show, :new, :index, :update]
  end

  resources :faqs, :only=>[:index], :as=>:faq
  get '/mobile/user' => "Mobile::User#index", :as=>:mobile_user_show
  get '/mobile/top' => "Mobile::User#top_nspre", :as=>:top_nspre
  get '/verify/email' => "Emails#verify_other", :as=>:verify_other_email

  resource :setting, :only=>[:show,:edit, :update]

  match '/mobile/register' => "api::Mobile#register", :as=>:api_mobile_register
  post '/mobile/image/upload' =>"api::Mobile#image", :as=>:api_mobile_image_upload

  get '/dashboard' => "dashboard#index", :as=>:dashboard

  get '/profile/:id' => "users#profile", :as=>:profile

  get '/noprofile' => "static_pages#no_profile", :as=>:no_profile

  post '/search'=>"search#show", :as=>:search

  post '/images/favorite/:id' => "images#favorited", :as=>:favorite_image
  post '/image/follow/:id' => "images#follow", :as=>:follow_user
  post '/image/unfollow/:id' => "images#unfollow", :as=>:unfollow_user

  get '/about'=>"static_pages#about", :as=>:about

  get '/:slug' => "images#thumb", :as=>:display_thumb
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  belongs_to :user
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_filter :authenticate_user!
  layout "application"

  def show

  end

  def edit
    @setting = current_user.setting
  end

  def update
    setting = Setting.find(params[:setting][:id] )
    setting.update_attributes(params[:setting])
    redirect_to edit_setting_url
  end

  def email_show

  end

end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/edit.html.erb
<%= render :partial=>"topbottom/header" %>

<script type="text/javascript">


(function($) {
    $(document).ready( function() {
                $("#enable-push").change( function() {
                    if ($("#enable-push").is(":checked") )
                        $("#push-table").show();
                    else
                        $("#push-table").hide();
                });

                // On load check the value of the radio button and adjust accordingly
                if ($("#enable-push").is(":checked") )
                    $("#push-table").show();
                else
                    $("#push-table").hide();
            }
    );
})(jQuery);

</script>

<div class="wrapper" id='wrapper_main'>

	<div class="center">
        <div style="margin-top: 10px;"><h2>Profile for <%= current_user.name || current_user.nickname %></h2></div>

		<div id="main">
           <div class="entry">
            <% #link_to( "Edit Emails", edit_email_url ) %>
            <%= form_for current_user.setting do |f| %>
                <%= f.hidden_field :id %>
                <%= f.label :profile, "Profile" %>:<br />
                <%= f.text_area :profile, :size=>"80x5" %>  <br />
                <%= f.label :newsletter, "Newsletter" %>
                <%= f.check_box :newsletter %> <br />
                 <%= f.label :enable_push_notification, "Enable Push Notification" %>
                 <%= f.check_box :enable_push_notification, :id=>"enable-push" %> <br />
                <table cellspacing="0" style="width: 50%; padding-bottom: 5px;" id="push-table">
                <caption>Push Notification Settings</caption>
                  <tbody>
                  <tr>
                    <th scope="row"><%= f.label :push_comment, "Comments" %></th>
                    <td><%= f.check_box :push_comment %></td>
                  </tr>
                  <tr>
                    <th class="alt" scope="row"><%= f.label :push_follow, "Follow" %></th>
                    <td class="alt"><%= f.check_box :push_follow %></td>
                  </tr>
                  </tbody>
                </table>

                <%= f.submit "Save", :class=>"button" %>
            <% end %>
            </div>
        <br />
        </div>  <!-- End Main -->
    </div> <!-- End Center -->

    </div> <!-- Main Wrapper -->


<%= render :partial => "topbottom/footer" %>

app/views/settings/email_show.html.erb
<%= render :partial=>"topbottom/header" %>

<div class="wrapper" id='wrapper_main'>

  <div class="center">
    <div style="margin-top: 10px;"><h2>Profile for <%= current_user.name || current_user.nickname %></h2></div>

    <div id="main">
      <div class="entry">
      <!-- Main Body of code -->
      </div>
      <br />
    </div>  <!-- End Main -->
  </div> <!-- End Center -->

</div> <!-- Main Wrapper -->


<%= render :partial => "topbottom/footer" %>