config/routes.rb
Clique::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :admins, :except=>[:new, :create, :destroy, :update, :show, :edit]
  mount RailsAdmin::Engine => '/wxztswe1', :as => 'rails_admin'

  root :to => "home#index"

  get '/i/:id'=>"images#show", :as=>:image_slug
  resources :images, :except=>[:create, :new, :destroy, :update] do
    resources :comments, :except=>[:show, :new, :index, :update]
  end

  resources :faqs, :only=>[:index], :as=>:faq
  get '/mobile/user' => "Mobile::User#index", :as=>:mobile_user_show
  get '/mobile/top' => "Mobile::User#top_nspre", :as=>:top_nspre
  get '/verify/email' => "Emails#verify_other", :as=>:verify_other_email

  resource :setting, :only=>[:show,:edit, :update]

  match '/mobile/register' => "api::Mobile#register", :as=>:api_mobile_register
  post '/mobile/image/upload' =>"api::Mobile#image", :as=>:api_mobile_image_upload

  get '/dashboard' => "dashboard#index", :as=>:dashboard

  get '/profile/:id' => "users#profile", :as=>:profile

  get '/noprofile' => "static_pages#no_profile", :as=>:no_profile

  post '/search'=>"search#show", :as=>:search

  post '/images/favorite/:id' => "images#favorited", :as=>:favorite_image
  post '/image/follow/:id' => "images#follow", :as=>:follow_user
  post '/image/unfollow/:id' => "images#unfollow", :as=>:unfollow_user

  get '/about'=>"static_pages#about", :as=>:about

  get '/:slug' => "images#thumb", :as=>:display_thumb
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :file, ImagesUploader
  before_save :generate_slugs
  belongs_to :user
  has_many :comments, :dependent => :destroy
  acts_as_taggable
  acts_as_voteable
  after_save :do_after

  def generate_slugs
    #Unqiue Slug
    loop do
      _slug = String.random_alphanumeric(7)
      if Image.find_by_slug(_slug) == nil
        self.slug = _slug
        break
      end
    end if self.slug.blank?

    self.delete_token = String.random_alphanumeric(7) if self.delete_token.blank?
    #self.md5=Digest::MD5.hexdigest( File.read( self.file.current_path ) ) if self.md5.blank?
    #Rails.cache.delete("gallery_images")
    #Rails.cache.delete("comments_image_#{self.id}")
  end

  def do_after
    if self.front_page?
      #send out front page newsletter
      if self.user.setting.newsletter? #send email
        Notifier.delay.front_page(self.id)
      end
    end
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  layout "application"
  #skip_before_filter :verify_authenticity_token, :only=>[:create]

  def index
  end

  def create

    user = User.find_by_mobile_token(params[:token])

    if not user.blank?
      img = Image.new
      img.file = params[:file]
      img.user_id = user.id
      img.save!
    end

    if user.blank?
      render :json=>{:message=>"Error with saving"}, :status=>:ok
    else
      if Rails.env.development?
        base_url = "http://localhost:3000"
      end
      render :json => { :slug=>img.slug, :url=>"#{base_url}#{img.file.thumb.url}", :delete=>img.delete_token }, :status => :ok
    end
  end

  def show
    @img = Image.find_by_slug(params[:id] )
    @date = @img.created_at.to_date
    @user = @img.user

    @favorite_count = @img.plusminus
    #@already_favorited = ImageService.has_user_favorited?(@user.id, @img.slug)

    @comments = @img.comments.order('created_at DESC').page params[:page] #@img.comments.order("created_at DESC").limit(100)

    @tags = @img.tag_counts_on(:tags)
    @voters = @img.voters_who_voted[0..19]

    @view_count = ImageView.increment @img.id

    render "show"
  end

  def thumb
    @image = Image.find_by_slug(params[:slug])
  end

  def favorited
    img = Image.find_by_slug(params[:id] )

    ImageService.addFavorite(img, current_user)

    if img.user.setting.newsletter?
      Notifier.delay.send_inspired(img.id)
    end

    render :nothing=>true
  end

  def follow
    @img = Image.find_by_slug(params[:id] )

    @user = @img.user
    current_user.follow( @user )

    if @user.setting.newsletter?
      Notifier.delay.following(@img.id)
    end

  end

  def unfollow
    @img = Image.find_by_slug(params[:id] )

    @user = @img.user
    current_user.stop_following( @user )

  end

end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_comment_box.html.erb
<% if not user_signed_in? %>
    Please <%= link_to( "Login", new_user_session_url) %> to leave a comment.
<% else %>
        <%=form_for [@img, Comment.new], :remote=>true do |f| %>
        Comment: <p><%= f.text_area :body, :size=>"80x4" %></p>
        <%= f.hidden_field :image_id, :value=>@img.id %>
        <%= f.hidden_field :user_id, :value=>current_user.id %>
        <%= f.submit "Add Comment", :class=>"button" %>
    <% end%>

<% end %>

app/views/images/_comments.html.erb
<h2>Comments</h2>
<% if @comments.blank? %>
    <h3 id="no_comment_title">No Comments. Be the first!</h3>
<% end %>

 <div class="entry commententries">
     <ol id="comments" class="commentlist">
        <%= render @comments %>
     </ol>
     <%= paginate @comments %>
 </div>

app/views/images/_tags.html.erb
<% tag_cloud(@tags, %w(tag1 tag2 tag3 tag4)) do |tag, css_class| %>
   <% #link_to tag.name, { :action => :tag, :id => tag.name }, :class => css_class %>
   <span class=<%=css_class%>><%= tag.name %> </span>
<% end %>

app/views/images/_user.html.erb
<span style="font-size: large; font-weight: bold;">Taken By: <a href="<%= profile_url(:id=>@user.slug) %>"><%= @user.nickname || "Anonymous" %></a></span> <br />
<span>Followers: <%= @user.followers_count %> <%= current_user.following?(@user) ? link_to( "Unfollow", unfollow_user_url(@img.slug), :remote=>true, :id=>"follow-link", :method=>:post) : link_to( "Follow", follow_user_url(@img.slug), :remote=>true, :id=>"follow-link", :method=>:post) if not current_user.blank? %> </span> <br />
<span class='rating_label'><%=link_to("Nspr'd Me", favorite_image_path(@img.slug), :id=>"favorite_link", :remote=>true, :method=>:post) if user_signed_in? and not @img.voted_by?(current_user) %> </span>

app/views/images/_voter.html.erb
<div style="float: left;">
    <%= image_tag( voter.avatar_profile_url, :width=>40, :height=>40, :padding=>"3px" ) %>
</div>

app/views/images/follow.js.erb
jQuery("#user-box").html("<%= j render :partial=>"user" %>");

app/views/images/index.html.erb
This is for my people

app/views/images/show.html.erb
<%= render :partial=>"topbottom/header" %>

<%= javascript_tag do %>
jQuery(document).ready( function() {
    jQuery("#favorite_link").bind("ajax:success", function(evt, data,status, xhr) {
        jQuery('#favorite_link').remove();
    });
});

    (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
    })();

    !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");

<% end %>

<div class="wrapper" id='wrapper_main'>

	<div class="center">



		<div id="main">

          <div class="content">

            <div class="entry">

              	<!-- ###################################################################### -->
				<div class="feature_wrap feature_wrap1">
				<!-- ###################################################################### -->
					<div class='featured_inside'>

							<div class="featured featured1" style="width: 640px; text-align: center;">

                              <%= image_tag(@img.file.url, :id=>"image-view", :alt=>"", :style=>"max_width: 640px; overflow: hidden; visibility: visible;") %>

							</div><!-- end .featured -->

					</div>
				<!-- ###################################################################### -->
				</div><!-- end featuredwrap -->
				<!-- ###################################################################### -->

               <div class="clean-gray-box">
                   <span class="date">
                        <span class='date_day'><%=@date.day %></span>
                        <span class='date_month'><%=@date.strftime("%^b") %></span>
                   </span>
                   <div class="entry-head bloghead">
                       <h1 class='siteheading'><%=@img.caption ||= "No Caption"%></h1>
                   </div>
                   <div class="entry-content">
                   </div>
               </div>

              <div class="clean-gray-box image-comments" style="overflow: hidden;">
                  <h2 style="display: inline; float:left;">People who are Nspre'd</h2> <br />
                  <div style="width: 100%; float: left;"><%= render :partial=>"voter", :collection=>@voters, :as=>:voter %></div>
              </div>

               <div class="clean-gray-box image-comments">
                 <%= render "comment_box" if user_signed_in? %>
                 <%= render "comments" %>
                 <div style="clear:both;">&nbsp;</div>
               </div>
            </div>

          </div>

          	<div class="sidebar" style="width: 240px;margin-left: 20px;">

                <div class="box" id="user-box">
                    <%= render :partial=>"user" %>
                </div>


                  <table cellpadding="0px" cellspacing="0px" style="float:left; position: relative; width: 260px; padding-bottom: 10px; margin-left: 1px;">
                    <tr>
                      <th style="text-align: center;">Views</th>
                      <th style="text-align: center;">Nspre'd</th>
                      <th style="text-align: center;">Comments</th>
                    </tr>
                    <tr>
                      <td style="text-align: center;"><%= @view_count %></td>
                      <td style="text-align: center;"><%= @favorite_count %></td>
                      <td style="text-align: center;"><%= @comments.count %></td>
                    </tr>
                  </table>


				<div class="box">
					<h3>Share With Friends</h3>
                     <fb:like send="true" layout="box_count" width="450" show_faces="false"></fb:like>
                     <g:plusone></g:plusone>
                     <a href="https://twitter.com/share" class="twitter-share-button" data-lang="en" data-url="<%=request.url %>">Tweet</a>
				</div>

                <% unless @tags.blank? %>
                    <div class="box">
                        <h3>Tags</h3>
                        <%=render "tags" %>
                    </div>
                <% end %>
			<!--end box-->
			</div>


        </div>  <!-- End Main -->
    </div> <!-- End Center -->

    </div> <!-- Main Wrapper -->
<%= render :partial => "topbottom/footer" %>

app/views/images/thumb.html.erb
<%= image_tag( @image.file.thumb.url ) %>

app/views/images/unfollow.js.erb
jQuery("#user-box").html("<%= j render :partial=>"user" %>");